# -*- mode: python ; coding: utf-8 -*-
#
# Build with:
#   uv run pyinstaller nebula.spec --distpath release --workpath release/build
#
# `dist/` is Vite's output and is emptied by every `pnpm build`, so the app is
# written to `release/` instead -- the two must not share a directory.
#
# Generated by PyInstaller from the invocation the packaging spike verified,
# then patched: paths made relative to the spec so it works from any checkout,
# and the Info.plist filled in.

import tomllib
from pathlib import Path

ROOT = Path(SPECPATH)

# Read rather than repeat, so the plist and the project cannot drift -- the
# spike found the plist saying 0.0.0 while pyproject said 0.1.0.
with (ROOT / "pyproject.toml").open("rb") as handle:
    VERSION = tomllib.load(handle)["project"]["version"]


a = Analysis(
    [str(ROOT / "src" / "nebula" / "__main__.py")],
    pathex=[str(ROOT / "src")],
    binaries=[],
    # Absolute paths: --add-data resolves relative to the spec's own directory,
    # which cost the spike a failed build.
    datas=[
        (str(ROOT / "dist"), "dist"),
        (str(ROOT / "assets" / "Nebula.icns"), "assets"),
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Nebula',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=[str(ROOT / "assets" / "Nebula.icns")],
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Nebula',
)
app = BUNDLE(
    coll,
    name='Nebula.app',
    icon=str(ROOT / "assets" / "Nebula.icns"),
    # Reverse-DNS is load-bearing, not cosmetic: with a bare name macOS starts
    # a second process per launch. With this, LaunchServices single-instances
    # the app, which is what closes PRD §15.
    bundle_identifier='com.giovanniiskandar.nebula',
    version=VERSION,
    info_plist={
        "CFBundleName": "Nebula",
        "CFBundleDisplayName": "Nebula",
        "CFBundleShortVersionString": VERSION,
        "CFBundleVersion": VERSION,
        "CFBundleIconFile": "Nebula.icns",
        "NSHighResolutionCapable": True,
    },
)
